#!/bin/bash

# wget "https://upload.wikimedia.org/wikipedia/commons/6/67/5ht2a.jpg"
# wget "https://upload.wikimedia.org/wikipedia/commons/2/25/DOI3Dan.gif"
# wget "https://upload.wikimedia.org/wikipedia/commons/b/b5/SigmoidFunction.png"
# wget "https://leonardoaraujosantos.gitbooks.io/artificial-inteligence/content/image_folder_4/Relu.jpeg"
# wget "https://upload.wikimedia.org/wikipedia/commons/6/60/ArtificialNeuronModel_english.png"
# wget "https://consumermediallc.files.wordpress.com/2017/05/notdogfull.jpg?w=1024&h=908"
# wget "https://storage.googleapis.com/deepmind-live-cms/documents/wavenet_conv_gif.gif"
# wget "https://upload.wikimedia.org/wikipedia/commons/e/eb/Stephen_Hawking.StarChild.jpg"
# wget "https://cdn-images-1.medium.com/max/1600/1*vEZE5VcjUr5RUbt_OWfR_w.gif"
# wget "https://s3.amazonaws.com/metafluidics-stage/wp-content/uploads/2015/11/14000142/300_final-800x600.jpg"
# wget "https://s3.amazonaws.com/metafluidics-stage/wp-content/uploads/2015/11/14001253/Fig1-800x600.png"
# wget "http://cdn3.bigcommerce.com/s-89v4ku3/products/195/images/526/SXSWAdEdit__30029.1487704062.1280.1280.jpg?c=2"
# wget "http://neuralnetworksanddeeplearning.com/images/tikz41.png"
# wget "http://neuralnetworksanddeeplearning.com/images/tikz43.png"
wget "https://upload.wikimedia.org/wikipedia/commons/d/dd/RecurrentLayerNeuralNetwork.png"